web/Controllers/CultureController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace web.Controllers
{
    public class CultureController : Controller
    {
        [HttpPost]
        public IActionResult SelectCulture(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewData["Title"]</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/css/bootstrap.min.css" />
    </environment>
</head>
<body>
    <div class="container">
        <header>
            <div class="row">
                <div class="col-sm-3 offset-sm-9 text-right">
                    @await Html.PartialAsync("_SelectCulturePartial")
                </div>
            </div>
        </header>
        @RenderBody()
    </div>
</body>
</html>

web/Pages/Shared/_SelectCulturePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocalizationOptions

@{ var requestCulture = Context.Features.Get<IRequestCultureFeature>();
                var cultureItems = LocalizationOptions.Value.SupportedUICultures
                    .Select(c => new SelectListItem { Value = c.Name, Text = Localizer.GetString(c.Name) })
                    .ToList();
                var returnUrl = string.IsNullOrEmpty(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}"; }
<div>
    <form id="selectLanguage"
          asp-controller="Culture"
          asp-action="SelectCulture"
          asp-route-returnUrl="@returnUrl"
          method="post"
          class="form-horizontal"
          role="form">
        <select name="culture"
                onchange="this.form.submit();"
                asp-for="@requestCulture.RequestCulture.UICulture.Name"
                asp-items="cultureItems"></select>
    </form>
</div>